/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nist.pms;

/**
 *
 * @author Rishika Gupta
 */
public class UserVeterinaary extends javax.swing.JFrame {

    /**
     * Creates new form UserVeterinaary
     */
    public UserVeterinaary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userbttn = new javax.swing.JButton();
        addmedicalinfo = new javax.swing.JButton();
        addpet = new javax.swing.JButton();
        petinformation = new javax.swing.JButton();
        lostfoundbttn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userbttn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userbttn.setForeground(new java.awt.Color(108, 168, 183));
        userbttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nist/pms/icons8-user-40.png"))); // NOI18N
        userbttn.setText("User");
        userbttn.setBorder(null);
        userbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userbttnActionPerformed(evt);
            }
        });

        addmedicalinfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addmedicalinfo.setForeground(new java.awt.Color(108, 168, 183));
        addmedicalinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nist/pms/icons8-vaccine-40.png"))); // NOI18N
        addmedicalinfo.setText("Add Medical Info");
        addmedicalinfo.setBorder(null);
        addmedicalinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmedicalinfoActionPerformed(evt);
            }
        });

        addpet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addpet.setForeground(new java.awt.Color(108, 168, 183));
        addpet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nist/pms/icons8-dog-35.png"))); // NOI18N
        addpet.setText("Add Pet");
        addpet.setBorder(null);
        addpet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpetActionPerformed(evt);
            }
        });

        petinformation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        petinformation.setForeground(new java.awt.Color(108, 168, 183));
        petinformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nist/pms/icons8-pet-35.png"))); // NOI18N
        petinformation.setText("Pet Information");
        petinformation.setBorder(null);
        petinformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petinformationActionPerformed(evt);
            }
        });

        lostfoundbttn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lostfoundbttn.setForeground(new java.awt.Color(108, 168, 183));
        lostfoundbttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nist/pms/icons8-alert-40.png"))); // NOI18N
        lostfoundbttn.setText("Lost And Found");
        lostfoundbttn.setBorder(null);
        lostfoundbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lostfoundbttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addmedicalinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(petinformation, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addpet, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lostfoundbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(userbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(addpet, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(addmedicalinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(petinformation, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(lostfoundbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nist/pms/pexels-tom-fisk-3765594_ccexpress.jpeg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userbttnActionPerformed
        // TODO add your handling code here:
        UserShow u = new UserShow();
        u.setVisible(true);
    }//GEN-LAST:event_userbttnActionPerformed

    private void addmedicalinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmedicalinfoActionPerformed
        // TODO add your handling code here:
        Addpet add = new Addpet();
        add.setVisible(true);
    }//GEN-LAST:event_addmedicalinfoActionPerformed

    private void addpetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpetActionPerformed
        // TODO add your handling code here:
        AddMedicalInfo pet = new AddMedicalInfo();
        pet.setVisible(true);
    }//GEN-LAST:event_addpetActionPerformed

    private void petinformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petinformationActionPerformed
        // TODO add your handling code here:
      PetInformation info = new  PetInformation();
      info.setVisible(true);
    }//GEN-LAST:event_petinformationActionPerformed

    private void lostfoundbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lostfoundbttnActionPerformed
        // TODO add your handling code here:
        lostanffoundveteran lost = new lostanffoundveteran();
        lost.setVisible(true);
    }//GEN-LAST:event_lostfoundbttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserVeterinaary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserVeterinaary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserVeterinaary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserVeterinaary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserVeterinaary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addmedicalinfo;
    private javax.swing.JButton addpet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lostfoundbttn;
    private javax.swing.JButton petinformation;
    private javax.swing.JButton userbttn;
    // End of variables declaration//GEN-END:variables
}
